Clarifies some parts of the assessment sheets
Allegheny-Computer-Science-203-S2019/cs203-S2019-assessment pull request #27
Opened 2019-02-22 19:25 UTC by huangs1

Edit some parts of the assessment sheets to clarify points.

2019-02-25 00:40 UTC, Michionlion requested changes

2019-02-25 00:40 UTC, Michionlion commented on assessment.md
> +    continous process
Typo: `continous` -> `continuous`

2019-02-25 00:40 UTC, Michionlion commented on assessment.md
> +  * E = All code effecitively utilizes many complexity reduction techniques such
Typo: `effecitively` -> `effectively`

2019-02-25 00:46 UTC, huangs1 commented on assessment.md
> +  * E = All code effecitively utilizes many complexity reduction techniques such
I have fixed the typo.

2019-02-25 00:46 UTC, huangs1 commented on assessment.md
> +    continous process
I have fixed the typo.

2019-02-25 01:06 UTC, Michionlion approved these changes

2019-03-04 03:34 UTC, Lancasterwu approved these changes
This looks good

2019-03-04 04:01 UTC, sutterj approved these changes

2019-03-15 17:42 UTC, toccinAC approved these changes

2019-03-15 17:43 UTC, merged